### ISSUE TITLE
Refactor: transaction-creation

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1158]
### Is your feature request related to a problem?

Currently we rework payments/invoices to match transactions within the screen views i.e.:
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/index.tsx#L200
We should try to handle this somewhere else. I.e. the dayjs part.
Only things that are not general should be handled in the view i.e. title/subtitle.

### Describe the solution you'd like

Find a way generalize this.

### Are you working on this?

No

**Comment by escapedcat** [comment]
Will be cleaned up with https://github.com/getAlby/meta/issues/15

**Comment by qqqzhch** [comment]
Is it because the transaction data format has changed, so the transaction display ui component has to be refactored?
@escapedcat

**Comment by escapedcat** [comment]
I believe this has been done - at least partly - by some PR @lujakob has done

**Comment by lujakob** [comment]
> I believe this has been done - at least partly - by some PR @lujakob has done

Yes I did some work on the mapping of transactions/payments data. 

https://github.com/lujakob/lightning-browser-extension/blob/97f7c75714a0508290faf4e1e0415197eadb1ba1/src/app/hooks/useTransactions.ts#L21

https://github.com/lujakob/lightning-browser-extension/blob/97f7c75714a0508290faf4e1e0415197eadb1ba1/src/app/utils/payments.ts#L16-L16

But I'm not sure if this is what was intended by this issue.

Anyways, we are currently refactoring getting outgoing transactions data from connectors and map IndexDB payment data on the fly, instead of getting all data from the IndexDB. There there will be more work done in this regard as well. Maybe this issue is deprecated and can be closed. @escapedcat what do you think?
