### ISSUE TITLE
Support all LNURLs from the send popup-screen

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#1216]
### Is your feature request related to a problem?

<img width="200" alt="image" src="https://user-images.githubusercontent.com/1016218/181875990-b60580fc-5f6e-4cd3-b2d2-2d386925f497.png">

- The input says: "Paste invoice, lnurl or lightning address"
- Not all LNURLs are actually supported through this

#### Follow up issues

- [ ] #1268
- [ ] #1269

### Describe the solution you'd like

LNURLs work via the prompt and one via the popup. But at least all prompt-supported ones should also work via the popup.

### Additional context

- current popup code:
    - https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/router/Popup/Popup.tsx#L36
    - https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Send.tsx#L37-L39
- prompt code:
    - https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/router/Prompt/Prompt.tsx/#L74-L121

The prompt code get's the details via the router. This should also be done in the popup router. If the functionality is the same it could be moved out.

### Are you working on this?

No

**Comment by bumi** [comment]
when I look at this then this manual loading of data from the URL and passing it in the props looks wrong to me: https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/router/Prompt/Prompt.tsx/#L28-L49

we have those two situations: 
1. the LNURL* components are rendered from the prompt. The prompt is opened from the `utils.openPrompt` function. There we pass the details in a query string. 
2. the LNURL* components are rendered in the popup and options page. There we navigate to those components.

Can we use some `state` that either gets populated when the prompt is loaded or passed in with the `navigate()` call? - instead of the props?

**Comment by bumi** [comment]
or can we load some page in the prompt which then also just navigates to the correct page? - to make sure the LNURL* components (and others) are always loaded the same way? 

`navigate("/lnurlChannel", {state: lnurlDetails })`

**Comment by bumi** [comment]
(actually we have this problem with keysend and other components, too

**Comment by reneaaron** [comment]
This should also cover lnurl-auth links, right? That would allow cross-device sign-ins (logging in on your mobile phone while Alby is installed your desktop PC), too! 💯

**Comment by escapedcat** [comment]
The base approach was merged. Further support will be done in split out tickets. See description above.
