### ISSUE TITLE
password - pin in Chrome Extension

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1255]
### Is your feature request related to a problem? Please describe

Password to Chrome Extension and Password to Alby Wallet is confusing.

### Describe the solution you'd like

- Rename the password to PIN
- Make it more clear, what this password is for
     -   This password is used to encrypt your data while stored on disk
     -  You need it to unlock your extension before using it on websites
     - This is not your GetAlby.com Account password
- Include a screenshot of where the user will enter this password again (instead of the sats symbol)

### Describe alternatives you've considered

See comments below

### Are you working on this?

No

**Comment by bumi** [comment]
//cc @reneaaron

**Comment by reneaaron** [comment]
Thanks for sketching this out @dvoroneca! 

The password (new: PIN) is used to encrypt sensible data that is stored on the disk (e.g. connection strings to nodes) and is used to decrypt this data while the user uses the extension.

While I totally see the value of changing to a PIN from the UX perspective, from the security perspective this is a quite big step backwards: 

A 4-digit PIN can easily be brute-forced within seconds. So if storing sensible data on the disk unencrypted is in our threat-model (which it should since we are handling admin macaroons, etc) I think we need to think about other solutions to this UX problem. 

I think a quick win would be to try to make it more clear during the onboarding screen:

![image](https://user-images.githubusercontent.com/100827540/183617760-a81185c3-2ffd-41bc-bcae-de2fc8c515cb.png)

Some ideas for that: 
 - Rename the password to PIN, anyway? (is it a problem if a PIN isn't a fixed, 4-digit number?)
 - Make it more clear, what this password is for
   - This password is used to encrypt your data while stored on disk
   - You need it to unlock your extension before using it on websites
   - This is not your GetAlby.com Account password
 - Include a screenshot of where the user will enter this password again (instead of the sats symbol)

![image](https://user-images.githubusercontent.com/100827540/183618501-0b067e8a-5738-459d-aa3d-81f5094d4d86.png)

**Comment by escapedcat** [comment]
I think this can be closed. We won't change the input-design.
Should we do the "rename to pin" with this ticket?

**Comment by bumi** [comment]
hmm. I like some of the ideas in here. for example also the screenshot that shows where the pin will be used. 
I think @reneaaron's ideas are a good, easy todo improvement.

**Comment by AnastasiaVolk** [comment]
@reneaaron 's list "Make it more clear, what this password is for" is very cool, helps with everything that may not be clear. And the screenshot, yes!

**Comment by escapedcat** [comment]
👍 updated the issue. I think this can just be done by everyone. We don't need an extra design for this anymore, right?
