### ISSUE TITLE
Error message when you switch an account in Alby to pay an invoice

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1329]
### Describe the bug
Leonardo reported the following back in our Telegram channel
https://user-images.githubusercontent.com/13707997/186353496-beff0697-47b1-4420-a64c-e7e36016479b.mp4

### To Reproduce
s. video

### Expected behavior
I guess, there should be no error message when you switch an account in Alby to pay an invoice. 

### Alby information
unknown

### Device information [optional]:
unknown

### Are you working on this issue?

No

**Comment by bumi** [comment]
we only have one global `connector` instance. the receive screen polls for invoice updates. 
when I switch the account a new connector is initialized and the next poll request to check for invoice updates is sent to that one. - this does not work because that new account does not know about the other invoice. 

can not be fixed now.

**Comment by reneaaron** [comment]
This can't be fixed right now, however we included a workaround that circumvents this problem by taking you to the wallet startpage whenever you switch accounts.
