### ISSUE TITLE
loadPayments is executed twice when Home is rendered

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#1350]
### Describe the bug

The loading/mounting of the home screen has to be reviewed. 

It seems `loadPayments` is executed twice - once when the allowance is set and once without. 
This leads to showing all payments even though there is an allowance set (and only the payments of that allowance should be shown)

### Screenshots

<img width="538" alt="image" src="https://user-images.githubusercontent.com/318/187081768-a2fc00f8-fff5-45c6-bf6b-7d8710b94c3f.png">

### To Reproduce

1. Make sure you have an allowance with payments
2. Open the popup
3. Only the payments of that website/allowance should be shown
4. But all payments a re shown

### Expected behavior

Home rendering needs to be reviewed and we must make sure that those functions are only called once.
And we must make sure that payments are loaded in the current allowance context - meaning when an allowance for the current website is available, then we only show payments of that website.

**Comment by bumi** [comment]
I think this was introduced with the settings change?

**Comment by escapedcat** [comment]
Relates and/or duplicates #1347

**Comment by lisabaut** [comment]
As discussed the loading of payments twice is not really a bug as the effect chain does work correctly.

The problem is that the `allowance` is taking longer to load than the loading of payments.

And if `allowance` changed, the loading of payment is called again as this is one of its dependencies.
=> see code https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/index.tsx#L150

To solve this we agreed on refactoring the whole Home screen with:

- [ ] divide view in two screens "Allowance"  and "Default"
- [ ] load allowance on mount
- [ ] if allowance exist => render Allowance Screen with already existing payments (`allowance.payments`)
- [ ] otherwise render Default view and load all payments from DB

**Comment by lisabaut** [comment]
I opened a new ticket for the Home Refactoring:
https://github.com/getAlby/lightning-browser-extension/issues/1359

And opened a PR to fix only this problem.
