### ISSUE TITLE
Your Websites page not showing some outgoing transactions [extension on Firefox]

### ISSUE THREAD

**Issue by tadeubas** [getAlby/lightning-browser-extension#1551]
### Describe the bug

When you check the extension Settings, the Websites tab don't show some transactions

#### The Websites page:

![1](https://user-images.githubusercontent.com/5518496/193462714-6fc0380d-1e52-496e-b8f0-208fd30cbb9c.png)

#### After clicked on the website to see more details:

![2](https://user-images.githubusercontent.com/5518496/193462722-c90af6cc-85de-446c-8ece-395d4d33ff58.png)

#### Details of the outgoing transactions, only one has a "link" attribute (it is the one that is listed on the Websites page):

![3](https://user-images.githubusercontent.com/5518496/193462739-cd840204-b250-44ff-82c2-e44c06d7f967.png)

### To Reproduce

1. Visit https://tippin.me/@turtle_btc
2. Click on the QRCode to copy
3. Click on Alby extension
4. Click on Send
5. Paste the invoice and make a payment
6. Visit https://tippin.me/@BitcoinQ_A
7. Click on the QRCode to copy
8. Click on Alby extension
9. Click on Send
10. Paste the invoice and make a payment
11. Click on Alby extension and access Settings
12. Check Websites tab
13. You will only see the first payment listed

### Expected behavior

Websites page should show all payments listed on a specific "Website"

### Alby information

- Alby Version: 1.16.1
- Alby installed through official Firefox page: https://addons.mozilla.org
- Wallet connected with Alby is custodial from Alby itself

### Device information [optional]

- OS: Windows 10
- Browser Firefox
- Browser Version 105.0.1 (64-bit)

### Are you working on this issue?

_(Yes/No)_ No

**Comment by escapedcat** [comment]
Hey @tadeubas , indeed this is confusing. Let me try to explain 🤞   

We recently updated the extension to not use "Alby" as a "website" anymore. Before we the code always got an "origin" from any "website" when you did a payment on it. But when you use "Send" directly form the extension-popup it used to grab the "origin" from the popup (which is also a "website"), which then just is "Alby" and then "Alby" will end up in your "used websites". That's why you see the extension string here:  
![image](https://user-images.githubusercontent.com/1016218/193497389-e9b4d445-9aca-4b41-8a41-9a3347fb0fa8.png)

This caused lot's of confusion so we changed it. Since then transactions being done in i.e. the popup via "send" will not be added to any "website". Because those were not made on a website.

You issue here is that your old txs still have these values and show up with an extension-string and the new ones do not.
This isn't a bug. It's basically "older data" being treated differently than "new data". The state of Alby is still changing a lot so these things will happen.
Do you understand my explanation? Was this helpful?
