### ISSUE TITLE
Display icon next to balance in the pop up or remove it if it cannot be displayed properly

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1567]
### Describe the bug

The (bee?) icon is not displayed properly on Chrome (Windows)

### Screenshots of the changes [optional]

![5kdjIvopc8](https://user-images.githubusercontent.com/13707997/194047938-4b2793bf-94df-4d13-8a44-8df3a113f4c4.png)

### To Reproduce

1. Open the extension
2. Select an Alby account 

### Expected behavior

a properly displayed icon or no icon at all

### Alby information

- Alby Version: [e.g. 1.5.0]
- Alby installed through [e.g. installed through the browser stores, installed manually]
- Wallet connected with Alby [e.g. LND, BlueWallet LNDhub]

### Device information [optional]

- OS: Windows
- Browser: Chrome and Firefox
- Browser Version: Chrome Version 105.0.5195.127

### Are you working on this issue?

No

**Comment by MoritzKa** [comment]
not super urgent. but fix should be quick anyway.

**Comment by rottingcleaner** [comment]
LNbits works great.

![Screenshot 2022-10-06 at 19 59 41(1)](https://user-images.githubusercontent.com/114179325/194385659-5f22c3aa-3268-4a8a-836d-b9c5c25676f5.png)

**Comment by escapedcat** [comment]
@rottingcleaner that name is short enough ;)
This i.e. looks bad:
![image](https://user-images.githubusercontent.com/1016218/194466853-18e81fb3-6d35-42a7-817d-7de4ebfa2961.png)


If it's longer it will break, because we use `substring`:  
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/components/AccountMenu/index.tsx/#L40  

I think this should be handled [via CSS (ellipsis)](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) instead of JS cutting of the string hard.
