### ISSUE TITLE
Docs: Unit tests fails for node versions mentioned in docs

### ISSUE THREAD

**Issue by vaibhavgarg237** [getAlby/lightning-browser-extension#1588]
### Describe the issue

_While doing development setup according to [documentation](https://github.com/getAlby/lightning-browser-extension#-quick-start) unit tests were failing._

### To Reproduce

1. `git clone https://github.com/getAlby/lightning-browser-extension.git`
2. `yarn install`
3. `yarn test:unit`
4. Either partial test cases fails, or some other error occurs

### Expected behavior

_All test cases must pass_

### Are you working on this issue?

_Yes_

**Comment by vaibhavgarg237** [comment]
Running tests on v16.16.0  ->  Partial tc's passes
```
Test Suites: 32 failed, 14 passed, 46 total
Tests:       21 passed, 21 total
Snapshots:   0 total
Time:        121.669 s
Ran all test suites.
error Command failed with exit code 1.
```


Running tests on v14.0.0 shows the below error

```
PS C:\Users\vaibh\OneDrive\Desktop\Dev\syncedProperly\lightning-browser-extension> yarn test:unit
yarn run v1.22.19
$ jest
C:\Users\vaibh\OneDrive\Desktop\Dev\syncedProperly\lightning-browser-extension\node_modules\@jest\reporters\build\GitHubActionsReporter.js:67
  #getMessageDetails(failureMessage, config) {
                    ^

SyntaxError: Unexpected token '('
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1106:15)
    at Module._compile (internal/modules/cjs/loader.js:1140:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\vaibh\OneDrive\Desktop\Dev\syncedProperly\lightning-browser-extension\node_modules\@jest\reporters\build\index.js:75:3) 
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
error Command failed with exit code 1.
```

**Comment by vaibhavgarg237** [comment]
Currently, these versions are failing!
```
_v14.0.0 - FAILED
v14.1.0 - FAILED
v14.2.0 - FAILED
v14.4.0 - FAILED
v14.5.0 - FAILED_

_v14.6.0 - PASSED    
v14.7.0 - PASSED    
v14.17.0 - PASSED    
v14.15.0 - PASSED    
v14.20.1 - PASSED
v15.0.0 - PASSED
v15.14.0 - PASSED
v16.00.0 - PASSED_

_v16.17.1 - FAILED_
```

**Comment by escapedcat** [comment]
Thanks for pointing this out!

Would you be interested to create a PR for this?
We could:
- Update these to the latest v14 version: 14.20.1
   - https://github.com/getAlby/lightning-browser-extension/blob/master/.node-version
   - https://github.com/getAlby/lightning-browser-extension/blob/master/.nvmrc
- This should say just say `=` instead of `>=`: https://github.com/getAlby/lightning-browser-extension/blob/master/package.json#L13
- Indicate that we only support v14 currently: https://github.com/getAlby/lightning-browser-extension#-quick-start 

On the long run we should update to 16 or 18, relates to #1314

**Comment by vaibhavgarg237** [comment]
> Thanks for pointing this out!
> 
> Would you be interested to create a PR for this? We could:
> 
> * Update these to the latest v14 version: 14.20.1

@escapedcat  I already created PR, yesterday with 14.20.1. Check out the below link.
https://github.com/getAlby/lightning-browser-extension/pull/1589

**Comment by vaibhavgarg237** [comment]
Updated changes for other files too...
Checkout updated files here https://github.com/getAlby/lightning-browser-extension/pull/1589/files

**Comment by escapedcat** [comment]
Thanks!

**Comment by bumi** [comment]
actually I can not believe that this is correct, what is the node 14 specific code? 

In this issue and in the PR there is no answer on what is not supported. what is the root cause here? 
Can you explain why only node 14 is supported? if we can not then we should not make such a change before knowing the details.
