### ISSUE TITLE
Inconsistent receive and send screens

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#1651]
### Describe the bug

copy withing the fields vs below the fields

### Screenshots of the changes [optional]

![Y9Yi7dJf5h](https://user-images.githubusercontent.com/13707997/197296846-81b71209-0a0c-40eb-a479-3b3d9f10ad0d.png)
![image](https://user-images.githubusercontent.com/13707997/197296897-79fd23f4-26d1-4b56-8202-77fc7e8e1c18.png)

**Comment by escapedcat** [comment]
We did this for this reason: #1517  
A placeholder is not a label and it's not a hint-text. It should show i.e. an example of what can be input there.  
If the text in there gets too long because languages are different it's being cut off and not useful anymore.  
To show the whole text on hover is not good UX.

Proposed solution:
- align "Receive" accordingly
- if the "hint"-text is too small let's i.e. make it bigger

**Comment by stackingsaunter** [comment]
Closing as this is the same as https://github.com/getAlby/lightning-browser-extension/issues/2061 and there's broader discussion there
