### ISSUE TITLE
Filter outgoing transactions by account

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1831]
### Feature description

The outgoing transaction list currently displays all transactions from all accounts but should be scoped to the current account in use. 

### Describe the solution

Save the account ID along with the [transaction data](https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/db.ts#L23) at the time of sending a payment and filter the outgoing transaction list by the current account in use.

**Comment by bumi** [comment]
keep in mind that old data does not have the ID - if we want to make sure it is there we have to see if we can write a data migration for that.

**Comment by reneaaron** [comment]
Do you agree that we should at least start saving the account id with the payments? I'd actually prioritize that a bit so we can migrate some day. Wdyt?

**Comment by stackingsaunter** [comment]
I think this is very much needed. This is very confusing that those tabs function differently.

When we align those to work the same, do you agree it will be useful to get rid of tabs and show just one transaction list? This is how it works in all (or almost all?) bitcoin/wallet products I've seen. During the journey mapping I've also seen a user confused and looking for a transaction that he did not see immediately because it was in the other tab.

**Comment by bumi** [comment]
@stackingsaunter generally, yes. but with the current setup this is technically not sooo easy. but we should approach this.
