### ISSUE TITLE
[BUG] Text should be inside the field

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text on send window should be inside the field, like the receive window.

### Screenshots [optional]

Send window with text outside the field:

![Captura de tela de 2023-02-04 10-48-04](https://user-images.githubusercontent.com/1178856/216771315-7bfc4f0e-246d-400c-b473-9d64599d5cb1.png)

Should be like receive window with text inside the field:

![Captura de tela de 2023-02-04 10-48-17](https://user-images.githubusercontent.com/1178856/216771340-e2272776-d54a-4ea3-8ba4-be81aeae87fe.png)

### Steps To Reproduce

1- Go to send window

### Expected behavior

See the text inside the field, like the receive window.

### Alby information

Alby: 1.25.1

### Are you working on this?

No

**Comment by escapedcat** [comment]
This current result was done on purpose because of #1517   

Placeholders are made to display input examples, not as a replacement for labels or hints I believe.  
In that case the hint-text (used as a placeholder displayed inside the input) was too long and gets cut off in some languages.

Might be better to check the extension and align this behaviour?  
wdyt @reneaaron @jankoegel @jakubszwedo

**Comment by bitcoinuser** [comment]
I don't care the text be cut. Why not mouseover on text and see the full text?

**Comment by escapedcat** [comment]
Why do you dislike the hint-text below the input?

> I don't care the text be cut. 

We need to consider more users though.

> Why not mouseover on text and see the full text?

Not very accessible. We should try to find a better way to handle this.

**Comment by jakubszwedo** [comment]
I agree with @escapedcat on this - the consensus is to to use a placeholder only to show examples of the input, MAYBE some hints, but as far as I research it's also advised to show them outside, especially if they are convening some important info - otherwise leave it empty. There shouldn't be any crucial information in there, which in the case of Send and types of input we can paste here, is quite important, so I'd leave it outside. We have a lot of space below so we can easily display the hint below the input. 

We could think of taking hints out of the input in the case of Receive screen. I think it's less crucial here, as the hints do not show any new information to the user, and are just a little helper. One could argue "amount in satoshis" does, but we use satoshis all over the extension, so it's not really new and we display fiat value all the time.

**Comment by bitcoinuser** [comment]
What about this idea?


https://user-images.githubusercontent.com/1178856/221208072-3086bc12-9778-4698-a603-a573bf13b07a.mp4

**Comment by bitcoinuser** [comment]
> I agree with @escapedcat on this - the consensus is to to use a placeholder only to show examples of the input, MAYBE some hints, but as far as I research it's also advised to show them outside, especially if they are convening some important info - otherwise leave it empty. There shouldn't be any crucial information in there, which in the case of Send and types of input we can paste here, is quite important, so I'd leave it outside. We have a lot of space below so we can easily display the hint below the input.
> 
> We could think of taking hints out of the input in the case of Receive screen. I think it's less crucial here, as the hints do not show any new information to the user, and are just a little helper. One could argue "amount in satoshis" does, but we use satoshis all over the extension, so it's not really new and we display fiat value all the time.

What I don't like is the font size. Is very small compared to other windows.

**Comment by bitcoinuser** [comment]
> Why do you dislike the hint-text below the input?

I don't dislike it, I dislike the font size that is very small compared to others windows.

**Comment by escapedcat** [comment]
> What about this idea?

This will lead to same issues. A label should be a short precise text to "label" the input. Not an lengthy explanation.

> What I don't like is the font size. Is very small compared to other windows.
> I don't dislike it, I dislike the font size that is very small compared to others windows.

In this case we could just think about updating the style of that hint-text I guess.  
The smaller size should just somehow show that this is not normal text but belongs to the input.
@stackingsaunter you got an idea what could be done here?

**Comment by stackingsaunter** [comment]
@escapedcat 12px for under-input text is quite common, I think this is the most common size for that thext, eg. Material Design uses precisely 12px. I think bigger font there will be disctracting
<img width="289" alt="Screenshot 2023-03-02 at 12 51 40" src="https://user-images.githubusercontent.com/68239231/222420978-9cdc1bde-6a98-412d-98aa-293351c40422.png">

The only way to make it bigger is to take this text out and use normal paragraph, but hmm I don't think that looks better?

<img width="652" alt="Screenshot 2023-03-02 at 12 53 31" src="https://user-images.githubusercontent.com/68239231/222421377-791b9e6b-32d4-401e-b817-ac7d69f6d1fe.png">

**Comment by escapedcat** [comment]
> 12px for under-input text is quite common, I think this is the most common size for that thext, eg. Material Design uses precisely 12px.

Agreed, that's why I styled it this way. This seems common practice to me.

I don't think this is urgent. We could leave it for now and see if we get any further feedback in the future.
