### ISSUE TITLE
[BUG] cannot send payment to some lightning addresses that start with a capital letter

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Entering a capital letter in a lightning address sometimes fails. It only happens with some domains so I think it would be best for us to convert to lowercase before sending the request.

### Screenshots [optional]

![image](https://user-images.githubusercontent.com/33993199/233785037-7e58db2b-821f-42d9-8693-aaab0672a6e7.png)

### Steps To Reproduce

1. Click send and paste "Zap@markshaw.bIz"
2. Try to pay

### Expected behavior

payment works

### Alby information

1.28.1

### Are you working on this?

None

**Comment by bumi** [comment]
This is an error on the lightning address server side. I don't think clients should do anything there.

**Comment by rolznz** [comment]
This is for a user who is using a custom domain for an Alby lightning address.

Email addresses aren't case sensitive, should lightning addresses be? I can see users fail to make payments because of this (accidentally, badly-made forms + Mobile automatic uppercase first character etc)

**Comment by bumi** [comment]
it’s up to the server implementation. It is just HTTP. That lightning address server needs to fix that. That’s a flaw on their side and they need to fix that. On 22. Apr 2023, at 17:03, Roland ***@***.***> wrote:﻿
This is for a user who is using a custom domain for an Alby lightning address.
Email addresses aren't case sensitive, should lightning addresses be? I can see users fail to make payments because of this (accidentally, badly-made forms + Mobile automatic uppercase first character etc)
