### ISSUE TITLE
Delete all data when resetting the extension

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#2435]
### Describe the bug

When you currently reset the extension (because you have forgotten the password, etc) only the connectors data is deleted, but not the payment data recorded in the extension. 

Therefore `src/extension/background-script/actions/setup/reset.ts` should be enhanced and also reset all data saved in other places (mainly `browser.storage` comes to mind here).

### Steps To Reproduce

1. Send an outgoing transaction
1. Reset the extension by typing a wrong unlock password and click the reset link
1. Walk through the onboarding flow again
1. Outgoing transactions are still being displayed

### Expected behavior

After resetting the extension all data should be gone.

**Comment by taboca** [comment]
May I work on this one?

**Comment by fczuardi** [comment]
Yes, I was able to reproduce it, the accounts I have to setup again, but Connected Websites and Outgoing Transactions are preserved from before the resetting.

**Comment by taboca** [comment]
Yes https://github.com/getAlby/lightning-browser-extension/issues/2435#ref-pullrequest-1721025257

**Comment by fczuardi** [comment]
hi @reneaaron , we ( @taboca, @mquasar and me) submitted a patch that includes the indexed db clears, so the Outgoing transactions should clear now.

**Comment by taboca** [comment]
When we approached this part of the code [with the 3 heads team session 33 yesterday] we celebrated a bit of advancement which does not clears out the need to understand the archictecture. 

Aside from the actual fix, I think it is worth to understand the logic and the strategy in place and what could happen in the future. To start the line of learning, indeed the browser.storage appears as a sort of "logical" one place or source of truth to make a developer-user think something like "Wait, I can clear my entire browser storage by hand and that is it". 

But then, as the attempt didn't work, I caught myself learning about how the browser's IndexDB infrastructure was also used with an extra layer on top, Dexie, which triggered the mind to think "Ah, maybe this code might need to do lot of DB-like operations, queries for example". 

Which brings me to throw this line of inquiry just wondering if anyone that touched more this part of the code can add thoughts from a more strategic or architectural point of view. Some ideas that crossed my mind when looking at parts of the code: 

* It seems that DB-like operations, queries, delete, insertions and such, are needed because UI-originated actions (perhaps other server actions too?) create need for quick DB-like operations. 
* It seems that the DB schema for the DB records are needed to be versioned because app changes over time. 
* It seems that IndexDB data is being kept, sometimes in IndexDB browser API, and other times in memory with an in memory IndexDB. 
* It seems that browser.local simple storage (TEXT-based) is used, perhaps for things that depends less on queries and DB-like manipulation. 
* It seems that the browser.local simple storage mechanism is also used (I didn`t confirm this case) to save DB state in browser.local when IndexDB is not available. Therefore, when it is available, there seems to be two persistent DBs. 
* It seems that there is a concept of migrations, or browser setup, that happens in init time that deals or checks,or deals with, memory-based vs. persistant-db.
* It seems that some synchronization mechanisms are in place. 

Apologies for lack of precision even with wording.
