### ISSUE TITLE
[BUG] Causes craigslist website to not work (blankness)

### ISSUE THREAD

**Issue by steveja42** [getAlby/lightning-browser-extension#2462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I installed the Alby extension on Brave browser and then the craigslist website,https://ksu.craigslist.org/,  stopped working, that is to say it is just blank instead of showing content. When I disable the Alby extension the craigslist website works as expected again.

### Steps To Reproduce

1. install Alby extension on Brave browser (perhaps others too)
2. Visit https://ksu.craigslist.org/  .  It is blank instead of showing page content.
3. Disable the extension and refresh the webpage and it will display properly.

### Expected behavior

To display the usual website content.

### Alby information

Alby 2.0.1
installed from chrome web store.

### Device information

Windows
Brave

### Are you working on this?

None

**Comment by reneaaron** [comment]
Thanks for the report @steveja42, however I fail to reproduce this. Could you maybe try to isolate this issue by disabling all other extensions than Alby and seeing if the problem still persists? 

If the error still appears, could you maybe have a look into the developer console of your browser and see if there are any errors that might be relevant?

**Comment by fczuardi** [comment]
on Alby 2.1.1 I + Firefox I think I was able to reproduce it by opening the same url on new tabs, once every 4 times, here is what I have in the console:

![image](https://github.com/getAlby/lightning-browser-extension/assets/7760/611ed31d-8111-4f0a-a8f4-40e3c6312c71)

so steps to reproduce for me was:

1. open a new tab
2. paste `https://ksu.craigslist.org/` in the location bar and type enter
3. repeat 1 a 2 several times

**Comment by fczuardi** [comment]
disabling Alby extension I was not able to reproduce it

**Comment by fczuardi** [comment]
here is a screenshot of the Network tab when the page  works:

![image](https://github.com/getAlby/lightning-browser-extension/assets/7760/77ec43dd-0cc5-44b7-9b87-e54da309b3f5)

and here when the page dont work:

![image](https://github.com/getAlby/lightning-browser-extension/assets/7760/3036d734-a5f3-4f2d-9780-54e5f17bee5a)

**Comment by GabrielSoga** [comment]
I was able to reproduce the issue on Chrome and this was the error on console:

![image](https://github.com/getAlby/lightning-browser-extension/assets/19688935/423e9ee5-3388-4324-908f-dcfd53595ea6)

I wonder if it's related to the `injectScript.js` since it's the only reference to the `insertBefore` method.

**Comment by fczuardi** [comment]
From an initial debugging of the craigslist code, there is a function that relies on the first `script` tag on the page to inject some css, and from an initial scan on alby code, alby does some manipalation on script tags as well, there might be an intermitent conflict between the two scripts (craigslist page and alby extention injections)

**Comment by reneaaron** [comment]
@fczuardi Thanks for your detailed analysis, that helped a lot to understand the problem here. :muscle: 

I think the way to solve this is to inline the scripts (instead of loading them via a request) because that allows to drastically minimize the time those injected script tags are on the page (time between `insertBefore` and `onload` callback in https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/content-script/injectScript.ts#L4) and therefore reduce side effects on websites that rely on this behavior. 

That however might not be a trivial task since it requires to change how the inpage scripts are built, etc. 

For future reference:
https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/contentscript.js#L72-L83

**Comment by fczuardi** [comment]
Do we need to remove the script tag at all? what would be the problem of leaving the scriptEl in the page? 

Another approach would be to insert our script tag somewhere else instead of as the very first child of the head element... 

I haven't tested either of those approaches, but if the issue with craigslist is just the fact that both scripts relies on the 1st script tag, then we could try to make alby's scrit tag be the latest in that order.

**Comment by reneaaron** [comment]
That could for sure work for this particular site, but it could potentially break other sites (that rely on the last element, etc), right?  

The reason we add it at the very first element is that it minimizes the time until `WebLN` is available to the website during the page load.

**Comment by reneaaron** [comment]
Thanks everybody for reporting & debugging this issue, this should finally be solved with #2691. :100:
