### ISSUE TITLE
[BUG] Unlock password gets used as nostr private key

### ISSUE THREAD

**Issue by Giszmo** [getAlby/lightning-browser-extension#2489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My password manager generated a "safe password" when starting the extension for the first time and I found that password again as the Nostr -> private key:

![Screenshot from 2023-06-15 20-31-50](https://github.com/getAlby/lightning-browser-extension/assets/96378/d4a760b0-3aa8-47cb-87b4-3be93fb81570)

Now I "generated a new key" but the nsec got then replaced by the password again. I suppose the npub relates to the valid nsec still.

### Steps To Reproduce

1. install Alby
2. try to use it

### Expected behavior

the nsec field should not trigger the password manager to think this was the same as the unlock password

### Alby information

Alby 2.1.1

### Device information

Debian
FF 96.0.3 (64-bit)

### Are you working on this?

None

**Comment by fczuardi** [comment]
I was able to reproduce it on **Firefox**, so if I understand it correctly, your issue is:

1. On the welcome screen (`moz-extension://xxxxx/welcome.html`) where you are prompted to enter an "unlock passcode", you used Firefox's built in password manager to generate a strong password.
2. Then later, after creating or connecting a lightning account, you went to the options of the account page (`moz-extension://xxxxxxx/options.html#/accounts/yyyyyyyyy`
3. On that page, that also have a password type text input field without username. Firefox tried to help and autocompleted the empty Nostr Private Key field with your unlock passcode

Is this description of your issue accurate?

If so, maybe this might be a Firefox behavior thing, and I dont know If there is something we can change on the extention's html pages to prevent that confusion. (rewrite the options.html page in a way that makes Firefox consider the Public Key field as the username? we can try that...)

Here is how the extention pages entries look on the `about:logins` page from firefox:

![image](https://github.com/getAlby/lightning-browser-extension/assets/7760/4459a690-3074-4425-8e9d-350f0413b3f7)

**Comment by fczuardi** [comment]
Firefox apparently only allow 1 password for each username on a website. And "no username" counts as one username, see that I tried to manually add a seccond password for website `moz-extension://ad4cac01-2dfd-496f-9fe8-d9bb6d1458e4` here and it didnt allowed:

![image](https://github.com/getAlby/lightning-browser-extension/assets/7760/8bf62a86-3ef6-475c-84a5-fe669b747ec0)

**Comment by fczuardi** [comment]
I don't know if such approach would be to hacky or not, but we could use a "fake username" hidden field on the set unlock passcode page just to prevent Firefox of having two pages where it can suggest the password of the "no username" user.

A quick test on my dev extension showed promising results with that approach. Me, @gabrielsoga and @mquasar can draft a possible fix.

**Comment by fczuardi** [comment]
@Giszmo I have submitted a patch here: https://github.com/getAlby/lightning-browser-extension/pull/2497 can you test that branch?

**Comment by Giszmo** [comment]
Not sure when I will get to that. Quite frankly I found Alby very confusing coming from the Nostr/zapping angle so I'm not even sure I want to use Alby.

**Comment by reneaaron** [comment]
Interested to learn more @Giszmo! Would you be willing to share what was confusing for you? We'd love to hear your feedback and improve on it! :blush:

**Comment by stackingsaunter** [comment]
@Giszmo I'd love to talk with you (audio/video) to get your feedback If you have time!

**Comment by pavanjoshi914** [comment]
closed in favour of #2595

**Comment by fczuardi** [comment]
Hey @reneaaron @pavanjoshi914, can we reopen this issue?

The merged branch did not fixed the problem of Firefox password manager asking to save the nostr private key as the "(no username)" user's password, and saving it overwrites the main wallet unlocking passcode. See screenshots below:

![01-Firefox-prompt-Screenshot_20230731_214948](https://github.com/getAlby/lightning-browser-extension/assets/7760/b5ff0dee-89cb-46aa-b5e4-211010af7ba1)
![02-Alby-with-unlocking-password-filled-Screenshot_20230731_215430](https://github.com/getAlby/lightning-browser-extension/assets/7760/bb0ce2d0-4c44-4158-9c77-ea64eb59dbb4)
![03-Alby-with-unlocking-password-visible-Screenshot_20230731_215509](https://github.com/getAlby/lightning-browser-extension/assets/7760/6dc8c79a-a667-4530-8116-bd14488c6ba1)

I still think that using a hidden input for the account name could be a fix for this, the patch is this: https://github.com/getAlby/lightning-browser-extension/pull/2497
