### ISSUE TITLE
[Feature] nostr relays should be configurable

### ISSUE THREAD

**Issue by badonyx** [getAlby/lightning-browser-extension#2823]
### Feature description

Relay list for NIP-07 `getRelays` should be configurable in settings instead of hardcoded here:

https://github.com/getAlby/lightning-browser-extension/blob/62ae77c52a65ff1c3b67701d95422c8a14096bf7/src/extension/background-script/actions/nostr/getRelays.ts#L15-L26

### Describe the solution

Configurable in settings.

### Are you working on this?

None

**Comment by Yeghro** [comment]
I second this.  The existing default list is out of date as well resulting in clients making repeated unnecessary attempts to connect to relays that don't response for whatever reason.

**Comment by rolznz** [comment]
I also came across this issue because NDK tries to use these relays by default which leads to a poor experience.

@badonyx @Yeghro is there any benefit to configuring this rather than just removing this optional method and leaving it up to the app to choose its boostrap relays? it's difficult for Alby to keep these relays up to date and choose "what is a good relay", so I'm not sure it even makes sense.

**Comment by Yeghro** [comment]
@rolznz That would be a better approach.  The apps can be configured to just fetch relays list associated with the users pubkey.  Shouldn't be too complicated.

**Comment by rolznz** [comment]
I am not sure it is the right path to enable managing relays in the Alby Extension as currently it simply acts as a signer. If there is more nostr functionality built in later, maybe this would make more sense. And in order to fetch a relays list associated with the user's pubkey, the extension needs to have at least one relay in common with the ones the user posted their relay list to.

For now I think the simpler and more effective option is to just remove this method.

**Comment by itstomekk** [comment]
would be nice if user could customize it in the extension...

So you could bring your relays with you to multiple clients, otherwise I'm actually never sure what relays do I use, if Primal has same as Nostrudel etc...
