### ISSUE TITLE
[BUG] Can't create invoice, can't redeem LNURL-withdraw

### ISSUE THREAD

**Issue by freerko** [getAlby/lightning-browser-extension#3099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I use the Alby extension in Firefox. I installed it a year ago or so to use it with Nostr but used it as well to receive some onchain transactions via a third-party website. Now I want to sent out an onchain transaction via another third-party service (deezy.place) to another wallet. For that I need some satoshis in the Alby-Wallet (Lightning). But somehow my Alby extension seems broken and I can't get any sats into my wallet.

How can I receive satoshis via Lightning in Alby?

### Steps To Reproduce

- When I click on "receive" in the wallet I only see an invalid QR-code, not even the normal camera app can read it. Clicking on the copy-button below the qr-code I get a confirmation that something was copied, but my clipboard is empty. 
- When I try to create a lightning invoice with any amount I just see the spinner after clicking on "Create Invoice". 
- If I click on "Bitcoin address" I am told to login on getalby.com but AFAIK I only have a local account. 
- When I paste a valid LNURL-withdraw code in the "Redeem" option Alby parses it correctly but after a click on "Confirm" I just see the spinner

### Expected behavior

AFAIK it should be possible to use Lightning in the Alby extension

### Alby information

Alby 3.6.0

### Device information

Firefox 123.0.1 on Ubuntu 23.10

### Are you working on this?

No

**Comment by freerko** [comment]
How can I use my Alby seed backup? Adding a new wallet to Alby on another computer I can only select "Other wallets" (without lightning/nosts), Voltage cloud or Alby account with invitation code (which I don't have). Is there any other way to use the seed backup in Alby?

**Comment by reneaaron** [comment]
I am sorry to hear that, would you mind sharing some logs? That would help us debug this problem further. 

https://guides.getalby.com/user-guide/v/alby-account-and-browser-extension/alby-browser-extension/debugging/mozilla-firefox

I think the website you mentioned used your nostr key to receive / send these onchain transactions. In order to use the Alby Extension you need a lightning wallet (that has always been the case), so either you use your own node or you sign up for any of the available options. Are you sure you didn't sign up for an Alby account back then? 

As soon as you connected your extension to any lightning wallet you should be able to top up your account with some bitcoin via lightning and then use these funds to send out some onchain transactions.

**Comment by freerko** [comment]
Thanks, I wasn't aware that I always need an external lightning wallet. For me it looks like lightning is included and the GUI offers me the option to create an lightning invoice, it would be great to get a notice that I first need to connect a lightning wallet.
I solved my issue already by importing my private key in the Alby installation of a friend :)
