### ISSUE TITLE
Add schma.org base metadata to transactions. Including Go-To "Actions"

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#454]
Currently we have a payment that stores certain meta data like the website URL, title, etc. 
Our goal is to make that transaction information more useful to the user and I am thinking of a transaction rather as an "interaction point" with the publisher.

So for example: 
* paying for for a song should include metadata about the song and an action where to play that song
* buying for a long/short position on a trading platform should include relevant metadata and an action where to close the position
etc.

To enable that I though to attach [schema.org](https://schema.org/docs/schemas.html) based microdata to each transaction.
Schema.org is rather widely adopted (e.g. [Google uses it](https://developers.google.com/gmail/markup)) and has a good set of standards.
And it is a simple JSON-LD document that we can store to each transaction.

Have a look at the exhaustive list of schemas: https://schema.org/docs/schemas.html

e.g. for an [audio object](https://schema.org/AudioObject), [Movie](https://schema.org/Movie), ... here is the [full list](https://schema.org/docs/full.html)

**Comment by legendarykamal** [comment]
Hi @bumi checking by if the issue description is still upto date , I would like to work on this issue.

Please assign me , Thanks.

**Comment by rolznz** [comment]
@legendarykamal unfortunately I think this issue is out of date.

There is a problem with only storing the metadata in the extension: the metadata is only accessible from the extension you used to pay the invoice, but not any other wallet.

Also, the schema.org schemas only describe the content (e.g. how long the song is), but not how to attach metadata about the payment along with the content. (e.g. when within the song the payment was made)

We are looking at storing this data using LUD-18 rather than in the extension, however there are still quite a few things to consider here and no tasks we can assign right now.

@bumi I will close this issue for now, let me know if you disagree

**Comment by legendarykamal** [comment]
Hey @rolznz I saw LUD-18 here https://github.com/lnurl/luds/blob/luds/18.md 

Would be happy to hear more on the things that we would like to consider here. Can we connect somewhere ?
 
I am present in the bitcoindesign.slack.com as well as discord or any other medium would be fine too. Thanks.
