### ISSUE TITLE
Provide a LNDHub connector without BlueWallet brand

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lightning-browser-extension#576]
In getalby.com/login we give users the possibility to import the Lightning Address account into the Alby extension using the LNDhub connector. Currently this connector is branded with BlueWallet. Now I would like to see a neutral LNDHub connector without a BlueWallet branding. That might be less confusing for the user.

**Comment by secondl1ght** [comment]
Just to confirm you are talking about this screen right?

![image](https://user-images.githubusercontent.com/85003930/152080763-37ebd8a7-fd59-41b6-9fa3-f50cb5de3b7a.png)

So you want to have a second LNDhub connector with the same functionality but with different branding? What branding would you like to see instead of the Blue Wallet?

**Comment by bumi** [comment]
@johnsBeharry do you have an idea what icon/logo we can use that indicates LNDhub is for BlueWallet and other services that use lndhub?

**Comment by secondl1ght** [comment]
Do we want to use our new LNDhub.go logo for this?

**Comment by escapedcat** [comment]
> Do we want to use our new LNDhub.go logo for this?

Should we just use this one as 2ndlight suggested?  
https://github.com/getAlby/lndhub.go/blob/main/static/img/logo.png
<img src="https://github.com/getAlby/lndhub.go/blob/main/static/img/logo.png?raw=true" />

**Comment by MoritzKa** [comment]
Let´s use it.
