### ISSUE TITLE
Use i18n for the whole app

### ISSUE THREAD

**Issue by escapedcat** [getAlby/lightning-browser-extension#781]
### Is your feature request related to a problem?

#711 added support for i18n-translation.  

As a first example [this headline was translated](https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/router/Welcome/Welcome.tsx/#L88
).  
Translations (for i.e. English) will be maintained [in this file.](https://github.com/getAlby/lightning-browser-extension/blob/master/src/i18n/locales/en.json)

### Describe the solution you'd like

All other strings in the app need to be replaced by i18n-placeholders and moved to the `en.json`.  
It should be somewhat possible to guess where a certain string is being used by looking at a structured json-file.

Could be good to look at other projects using the same plugin, i.e. 
- https://github.com/cstenglein/raspiblitz-web/blob/master/src/i18n/langs/en.json
- ...happy for further examples

This can be done in multiple steps. If you are interested to give this a try maybe start with a PR for one section first and get feedback first before moving on.

### Are you working on this?

No

**Comment by pavanjoshi914** [comment]
thanks willing to push translation pr's as soon  as possible

**Comment by escapedcat** [comment]
Via Weblate after approving the OSS libre hosting plan:  

> Don’t forget to mention you use Weblate in the README and the website of your project! You can use the lovely stuff from the Share menu of your Weblate project for it.

Let's support them with mentions.

**Comment by thebrandonlucas** [comment]
Hello, I've started working on this [here](https://github.com/getAlby/lightning-browser-extension/pull/883). This just includes the "welcome" pages since I wanted to receive feedback on that before doing more. Thanks!

**Comment by thebrandonlucas** [comment]
> It should be somewhat possible to guess where a certain string is being used by looking at a structured json-file.

@escapedcat Should we be optimizing for guessing where strings are in the code or guessing where they are in the UI? For example, in `en.json` in `welcome.choose_connector.alby`, I could add a key called `new_wallet` which contains all the strings for the Alby hosted wallet page, because the enclosing folder for the code with those strings is called `NewWallet`, or I could just name it something like `page` because it's the corresponding "page" under the `choose_connector.alby` key in the UI.

**Comment by escapedcat** [comment]
Good question. I think most projects I've seen so far are using a mix.  
On one hand you have certain "views" (i.e. a special headlien will only show up on one page) an on the other hand we have more general things like "forms" (i.e. a "sats" input mitht show up in different forms).

Does this help?

Also we have the option to enrich the data Weblate shows, i.e. here we added [a screenshot of view which can be added to several related strings](https://hosted.weblate.org/translate/getalby-lightning-browser-extension/getalby-lightning-browser-extension/de/?q=state:%3Ctranslated)'

**Comment by thebrandonlucas** [comment]
Yes that helps, I'll take a crack at following a pattern that best combines the particular with the general to optimize for clarity.

As far as Weblate goes, is there a way to export/import strings from/to json so that we don't have to do the duplicate work of adding strings in the repo and in weblate? I'm not really seeing how Weblate is directly connected to i18n in the project

**Comment by escapedcat** [comment]
> As far as Weblate goes, is there a way to export/import strings from/to json so that we don't have to do the duplicate work of adding strings in the repo and in weblate? I'm not really seeing how Weblate is directly connected to i18n in the project

That's already set up and working, no worries ;)

**Comment by escapedcat** [comment]
We will move in further translations step by step via future PRs
