### ISSUE TITLE
Wrong recipient showing when using Bitrefil, (Shows Alby recieved instead of Bitrefil)

### ISSUE THREAD

**Issue by Amyyalby** [getAlby/lightning-browser-extension#865]
Wrong recipient showing when using Bitrefil, (Shows Alby received instead of Bitrefil)

Visit Bitrefil, buy a gift card,  pop up payment successful to Alby, also the extension shows the recipient as Alby.

Should show Bitrefil as the recipient.

- Alby Version: 1.10.0
- Alby installed through Firefox
- Wallet connected with Alby

**Comment by escapedcat** [comment]
You got a screenshot of that maybe?

**Comment by bumi** [comment]
when manually paying an invoice we currently show Alby: 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/318/167251538-b423921a-5412-4540-af9b-c05690500fcb.png">

This is because we reused the default components where we assume that we have some recipient meta data. 
Not sure if there is an issue for this.

What we have to do is: specially handle manual payments. (and think about where/how we show those transactions that we do not associate with a website)

**Comment by bumi** [comment]
(even though on Bitrefill you should not need to pay manually. @Amyyalby can you describe how you paid? what exact steps did you do (where did you click, what did you copy, etc.)?

**Comment by bumi** [comment]
related: https://github.com/getAlby/lightning-browser-extension/issues/770

**Comment by escapedcat** [comment]
Yes, will be fixed with #770 :

<img width="200"  src="https://user-images.githubusercontent.com/1016218/187374108-4b5b1f5c-0c1b-4ce8-bcbd-a8abc74bef12.png" />
